spring:
  profiles:
    default: real
    group:
      real:
        - real
        - mysql
      stg:
        - stg
        - mysql
      test:
        - test
        - mysql
      sandbox:
        - sandbox
        - mysql
      dev:
        - dev
        - mysql
      action:
        - actions
        - h2